// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s440proto/440.proto

/*
Package s440proto is a generated protocol buffer package.

It is generated from these files:
	s440proto/440.proto

It has these top-level messages:
	Shop
	Response
*/
package s440proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Shop struct {
	Slug        string            `protobuf:"bytes,1,opt,name=Slug,json=slug" json:"Slug,omitempty"`
	Title       string            `protobuf:"bytes,2,opt,name=Title,json=title" json:"Title,omitempty"`
	Description string            `protobuf:"bytes,3,opt,name=Description,json=description" json:"Description,omitempty"`
	Config      map[string]string `protobuf:"bytes,4,rep,name=Config,json=config" json:"Config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Shop) Reset()                    { *m = Shop{} }
func (m *Shop) String() string            { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()               {}
func (*Shop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Shop) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Shop) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Shop) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Shop) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type Response struct {
	Message string `protobuf:"bytes,1,opt,name=Message,json=message" json:"Message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Shop)(nil), "s440proto.Shop")
	proto.RegisterType((*Response)(nil), "s440proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for S440Site service

type S440SiteClient interface {
	CreateSiteHandler(ctx context.Context, in *Shop, opts ...grpc.CallOption) (*Response, error)
}

type s440SiteClient struct {
	cc *grpc.ClientConn
}

func NewS440SiteClient(cc *grpc.ClientConn) S440SiteClient {
	return &s440SiteClient{cc}
}

func (c *s440SiteClient) CreateSiteHandler(ctx context.Context, in *Shop, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/s440proto.s440site/CreateSiteHandler", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for S440Site service

type S440SiteServer interface {
	CreateSiteHandler(context.Context, *Shop) (*Response, error)
}

func RegisterS440SiteServer(s *grpc.Server, srv S440SiteServer) {
	s.RegisterService(&_S440Site_serviceDesc, srv)
}

func _S440Site_CreateSiteHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Shop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S440SiteServer).CreateSiteHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/s440proto.s440site/CreateSiteHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S440SiteServer).CreateSiteHandler(ctx, req.(*Shop))
	}
	return interceptor(ctx, in, info, handler)
}

var _S440Site_serviceDesc = grpc.ServiceDesc{
	ServiceName: "s440proto.s440site",
	HandlerType: (*S440SiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSiteHandler",
			Handler:    _S440Site_CreateSiteHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s440proto/440.proto",
}

func init() { proto.RegisterFile("s440proto/440.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0xbf, 0x34, 0x69, 0xda, 0xde, 0x0c, 0x1f, 0xdc, 0x32, 0x58, 0x65, 0x89, 0x22, 0x86,
	0x4e, 0xa1, 0x6a, 0x33, 0xf0, 0x67, 0x2c, 0x08, 0x16, 0x96, 0x84, 0x17, 0x08, 0xed, 0x25, 0x58,
	0x18, 0x3b, 0xb2, 0x1d, 0xa4, 0xbe, 0x1e, 0x4f, 0x86, 0xec, 0x96, 0x50, 0xb1, 0xdd, 0xf3, 0x3b,
	0xba, 0x3a, 0x3f, 0x98, 0x9a, 0xa2, 0x58, 0xb4, 0x5a, 0x59, 0x75, 0x59, 0x14, 0x8b, 0xdc, 0x5f,
	0x38, 0xe9, 0x61, 0xf6, 0x15, 0x40, 0x54, 0xbd, 0xa9, 0x16, 0x11, 0xa2, 0x4a, 0x74, 0x0d, 0x0b,
	0xd2, 0x60, 0x3e, 0x29, 0x23, 0x23, 0xba, 0x06, 0xcf, 0x60, 0xf8, 0xcc, 0xad, 0x20, 0x36, 0xf0,
	0x70, 0x68, 0x5d, 0xc0, 0x14, 0x92, 0x3b, 0x32, 0x1b, 0xcd, 0x5b, 0xcb, 0x95, 0x64, 0xa1, 0xef,
	0x92, 0xed, 0x2f, 0xc2, 0x15, 0xc4, 0x6b, 0x25, 0x5f, 0x79, 0xc3, 0xa2, 0x34, 0x9c, 0x27, 0xcb,
	0xf3, 0xbc, 0x1f, 0xcc, 0xdd, 0x58, 0xbe, 0x6f, 0xef, 0xa5, 0xd5, 0xbb, 0x32, 0xde, 0xf8, 0x30,
	0xbb, 0x86, 0xe4, 0x08, 0xe3, 0x09, 0x84, 0xef, 0xb4, 0x3b, 0xe8, 0xb8, 0xd3, 0xd9, 0x7c, 0xd6,
	0xa2, 0xeb, 0x6d, 0x7c, 0xb8, 0x19, 0x5c, 0x05, 0xd9, 0x05, 0x8c, 0x4b, 0x32, 0xad, 0x92, 0x86,
	0x90, 0xc1, 0xe8, 0x89, 0x8c, 0xa9, 0x1b, 0x3a, 0xfc, 0x8e, 0x3e, 0xf6, 0x71, 0xf9, 0x00, 0x63,
	0xa7, 0x61, 0xb8, 0x25, 0xbc, 0x85, 0xd3, 0xb5, 0xa6, 0xda, 0x52, 0xc5, 0x2d, 0x3d, 0xd6, 0x72,
	0x2b, 0x48, 0xe3, 0xff, 0x3f, 0x9a, 0xb3, 0xe9, 0x11, 0xf8, 0x19, 0xc8, 0xfe, 0xbd, 0xc4, 0x9e,
	0xac, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x15, 0xee, 0x03, 0x62, 0x5c, 0x01, 0x00, 0x00,
}
